# Copyright (c) K-Society and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.
#

branches:
  only:
    - master
    - develop

image: Visual Studio 2022

version: 1.0.0.{build}
platform: Any CPU
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  LogSystemVersion: 0.0.0.0

#install:
#  - ps: .\dotnet-install.ps1 -Version '7.0.100'

before_build:
  - ps: dotnet --info

build:
  verbosity: minimal

build_script:
  - appveyor.cmd
  
after_build:
  - ps: $logSystemPath = Resolve-Path .\Src\00\KSociety.Log.Install\K-Society.Log-net6.0.exe; $array = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$logSystemPath").FileVersion -split "\."; $env:LogSystemVersion = $array[0] + "." + $array[1] + "." + $array[2]; Write-Host "$env:LogSystemVersion"
  - ps: Compress-Archive -LiteralPath .\Src\00\KSociety.Log.Install\K-Society.Log-net6.0.exe -DestinationPath .\Src\00\KSociety.Log.Install\K-Society.Log-net6.0.zip -Force
  - ps: Compress-Archive -LiteralPath .\Src\00\KSociety.Log.Install\K-Society.Log-net7.0.exe -DestinationPath .\Src\00\KSociety.Log.Install\K-Society.Log-net7.0.zip -Force

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

#build:
#  publish_nuget: true

artifacts:
  - path: build\**\Release\*.*nupkg
    name: nuget
  - path: Src\00\KSociety.Log.Install\K-Society.Log-net6.0.zip
    name: logsysteminstallernet6
  - path: Src\00\KSociety.Log.Install\K-Society.Log-net7.0.zip
    name: logsysteminstallernet7

deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/k-society/api/v2/package
    api_key:
      secure: jIQOXURv/wJ2bys5OTJpp+zTyN8tyVAnczeodJUK3Nw=
    skip_symbols: true
    symbol_server: 
    artifact: /.*\.nupkg/
    on:
      branch: /^(master|develop)$/
      
  - provider: NuGet
    server: 
    api_key:
      secure: U1qzBMTcpUuJ7GcLAiLJJkkQXQhqZcdnmYu7rTpxuidiMRCZtJ5Vr6DoTyx1wm3p
    skip_symbols: true
    symbol_server: https://www.nuget.org/api/v2/symbolpackage
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: master
         
  - provider: GitHub
    release: K-Society.Log $(LogSystemVersion)
    description: 'K-Society.Log $(LogSystemVersion)'
    auth_token:
      secure: ENcLoui/QOEIlADrbVlH5ZeIjOaJih6C65EM9p7Rs+KX45w7p8Y4J6KTHPRk5LbY
    artifact: logsysteminstallernet6, logsysteminstallernet7
    draft: false
    prerelease: false
    force_update: true
    tag: $(LogSystemVersion)
    on:
      branch: master
