name: Build KSociety.Log

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      tags:
        manual: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        uses: dotnet/nbgv@master
        id: nbgv
        run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'

      - name: Build KSociety.Log
        shell: cmd
        run: ./build.cmd

      #- name: Save build
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: artifacts
      #    path: build/**/Release/*.*nupkg

      

      - name: Zip Installer net6.0
      #  run: zip -r release.zip
        shell: pwsh
        run: Compress-Archive -LiteralPath .\build\KSociety.Log.Install\Release\net6.0\KSociety.Log.Install-1.1.80-net6.0.exe -DestinationPath .\build\KSociety.Log.Install\Release\net6.0\K-Society.Log-net6.0.zip -Force

      #- name: Zip Installer net7.0
      #  shell: pwsh
      #  run: Compress-Archive -LiteralPath .\build\KSociety.Log.Install\Release\net7.0\KSociety.Log.Install-1.1.76-net7.0.exe -DestinationPath .\build\KSociety.Log.Install\Release\net7.0\K-Society.Log-net7.0.zip -Force

      - name: Push to GitHub Packages
        if: github.event_name == 'push' && github.repository_owner == 'K-Society' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        run: dotnet nuget push "build/**/Release/*.nupkg" --source https://nuget.pkg.github.com/K-Society/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Push to NuGet Packages
        if: github.event_name == 'push' && github.repository_owner == 'K-Society' && (github.ref == 'refs/heads/master')
        run: nuget push build/**/Release/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
        